services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: on-failure
    env_file:
      - ./.env.development
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MONGO_INITDB_DATABASE: reveriedatabase
    secrets:
      - db_username
      - db_password
    ports:
      - 27016:27017
    networks:
      - backnet
  
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    restart: on-failure
    networks:
      - backnet

  reverie-api:
    build:
      context: ./reverie-api
      dockerfile: dev.Dockerfile
    image: reverie-api
    restart: 'no'
    env_file:
      - ./.env.development
    environment:
      NODE_ENV: development
      PORT: 8080
      CLIENT_ORIGIN: http://127.0.0.1:5173
      DB_USERNAME_FILE: /run/secrets/db_username
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME: reveriedatabase
      DB_URI_FILE: /run/secrets/db_uri
      EXPIRESIN: 10m
      EXPIRESIN_REFRESH: 1d
      ISS: http://127.0.0.1:8080
      SALTWORKFACTOR: 12
      PUB_KEY_FILE: /run/secrets/pub_key
      PRIV_KEY_FILE: /run/secrets/priv_key
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      JWT_SECRET_REFRESH_FILE: /run/secrets/jwt_secret_refresh
    secrets:
      - db_username
      - db_password
      - db_uri
      - pub_key
      - priv_key
      - jwt_secret
      - jwt_secret_refresh
    volumes:
      - ./reverie-api/:/app
    expose:
      - 8080
    depends_on:
      - mongo_db
      - redis
    networks:
      - backnet
    deploy:
      replicas: 10

  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - reverie-api
      - reverie-ui
    ports:
      - 7800:7800
    networks:
      - backnet
  
  reverie-ui:
    build:
      context: reverie-ui
      dockerfile: dev.Dockerfile
    image: reverie-ui
    volumes:
      - ./reverie-ui/:/app
      - vite_node_modules:/app/node_modules
    restart: 'no'
    expose:
      - 5173
    depends_on:
      - reverie-api
    env_file:
      - .env.development
    networks:
      - backnet
     
volumes:
  mongo_db:
  vite_node_modules:

networks:
  backnet:

secrets:
  db_username:
    file: ./app-secrets/db_username.txt
  db_password:
    file: ./app-secrets/db_password.txt
  db_uri:
    file: ./app-secrets/db_uri.txt
  pub_key:
    file: ./app-secrets/pub_key.txt
  priv_key:
    file: ./app-secrets/priv_key.txt
  jwt_secret:
    file: ./app-secrets/jwt_secret.txt
  jwt_secret_refresh:
    file: ./app-secrets/jwt_secret_refresh.txt