version: "3.4"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    env_file:
      - ./.env.development
    volumes:
      - mongo_db:/data/db
    networks:
      - backnet
  
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    networks:
      - backnet

  reverie-api:
    build:
      context: ./reverie-api
      dockerfile: dev.Dockerfile
    image: reverie-api
    restart: 'no'
    volumes:
      - ./reverie-api/:/app
      - express_node_modules:/app/node_modules
    expose:
      - 8080
    depends_on:
      - mongo_db
      - redis
    env_file:
      - ./.env.development
    networks:
      - backnet
     
volumes:
  mongo_db:
  express_node_modules:

networks:
  backnet: