### sanity check
GET http://localhost:7800/api/ HTTP/1.1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDgwYjJhZDBhMDZlZWUwNjkzMDNhMSIsInVzZXJuYW1lIjoidXNlcjEiLCJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsImlhdCI6MTY5OTIyMDMzMCwiZXhwIjoxNjk5MjI3NTMwLCJhdWQiOiI2NTQ4MGIyYWQwYTA2ZWVlMDY5MzAzYTEiLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwODAiLCJzdWIiOiJ1c2VyMUBnbWFpbC5jb20ifQ.4kYFDANakpa7JRQKMRABPH_6g5q8uA_Bf_p5kVEb5p0

### signup
POST http://localhost:7800/api/signup HTTP/1.1
Content-Type: application/json

{
    "username": "user1",
    "email": "user1@gmail.com",
    "password": "@passworD1#",
    "confirm": "@passworD1#"
}

### find user by id
GET http://localhost:7800/api/users/65480b2ad0a06eee069303a1 HTTP/1.1

### find all users
GET http://localhost:7800/api/users HTTP/1.1


### login
POST http://localhost:7800/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "@passworD1#"
}


### obtain refresh token
POST http://localhost:7800/api/refresh HTTP/1.1
Content-Type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTkyMTkwNjgsImV4cCI6MTcwMTgxMTA2OCwiYXVkIjoiNjU0N2Y5NmRlNDIzZmUyNTMzNjcyZTVjIiwiaXNzIjoiaHR0cDovLzEyNy4wLjAuMTo4MDgwIiwic3ViIjoiNjU0N2Y5NmRlNDIzZmUyNTMzNjcyZTVjIn0.kNapLWjhCaaPkMtTanwWyJKtgXTpRz5_jRKuEoZe7BA"
}


### get all posts
GET http://localhost:7800/api/posts/ HTTP/1.1
Content-Type: application/json


### find post by id
GET http://localhost:7800/api/posts/654c247e606da3cad57ec0a3 HTTP/1.1
Content-Type: application/json


### find post by slug
GET http://localhost:7800/api/posts/slug/sample-titlex HTTP/1.1
Content-Type: application/json



### add post
POST http://localhost:7800/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NGMyNDNkMzZlZmEzY2M1ODY1YThkYSIsInVzZXJuYW1lIjoidXNlcjEiLCJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsImlhdCI6MTY5OTQ4ODgzNCwiZXhwIjoxNjk5NDk2MDM0LCJhdWQiOiI2NTRjMjQzZDM2ZWZhM2NjNTg2NWE4ZGEiLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwODAiLCJzdWIiOiJ1c2VyMUBnbWFpbC5jb20ifQ.ZKkDVrb6DHxfMS0nS8u-4Onv11Vt-z4ivplVqw0X_rw


{
    "title": "Sample titleX",
    "description": "Sample descriptionX",
    "entry": "Sample entryX"
}




### update post
PATCH http://localhost:7800/api/posts/654c247e606da3cad57ec0a3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NGMyNDNkMzZlZmEzY2M1ODY1YThkYSIsInVzZXJuYW1lIjoidXNlcjEiLCJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsImlhdCI6MTY5OTQ5NDQ1MiwiZXhwIjoxNjk5NTAxNjUyLCJhdWQiOiI2NTRjMjQzZDM2ZWZhM2NjNTg2NWE4ZGEiLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwODAiLCJzdWIiOiJ1c2VyMUBnbWFpbC5jb20ifQ.vk5qtLyHHMjm7oZmUXTZQm6deVnFHFx4HHCEUIgql0A


{
   "title": "Sample title UpdatedX3",
    "description": "Sample description UpdatedX1",
    "entry": "Sample entry UpdatedX1"
}


### delete user by user id
DELETE http://localhost:7800/api/users/6547f96de423fe2533672e5c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDdmOTZkZTQyM2ZlMjUzMzY3MmU1YyIsInVzZXJuYW1lIjoidXNlcjEiLCJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsImlhdCI6MTY5OTIyMDE5MCwiZXhwIjoxNjk5MjI3MzkwLCJhdWQiOiI2NTQ3Zjk2ZGU0MjNmZTI1MzM2NzJlNWMiLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwODAiLCJzdWIiOiJ1c2VyMUBnbWFpbC5jb20ifQ.prJv-dSe6OVa1AD5dwy1OTY4VLKp7G7G58ekrOPFP3s


### delete post by post id
DELETE http://localhost:7800/api/posts/65481bd325bbc9bdbb20394c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDgxYmI4Mjk3MWQxNTUwOTQzNjRkMCIsInVzZXJuYW1lIjoidXNlcjEiLCJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsImlhdCI6MTY5OTIyNzI3NiwiZXhwIjoxNjk5MjM0NDc2LCJhdWQiOiI2NTQ4MWJiODI5NzFkMTU1MDk0MzY0ZDAiLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwODAiLCJzdWIiOiJ1c2VyMUBnbWFpbC5jb20ifQ.Ty8wQbbtT2YLRzu6D599L3KrjDITyMRWVzqsEvqjzUg



