services:
  mongo_db:
  image: mongo:latest
  container_name: mongo_container
  restart: always
  environment:
    MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
    MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
  env_file:
    - ./.env
  volumes:
    - mongo_data:/data/db
  ports:
    - '${MONGODB_CONTAINER_PORT}:${MONGODB_LOCAL_PORT}'


volumes:
  mongo_data: {}